### ISSUE TITLE
FileNotFoundException: /system/etc/security/cacerts.bks in ICS

### ISSUE THREAD

**Issue by tomwhipple** [moxie0/AndroidPinning#1]
It seems that Android 4.0.3 uses a different system trust store. As a result, code that works on 2.x fails on 4.0.

root@android:/ # ls /system/etc/security
cacerts
otacerts.zip

root@android:/ # ls /system/etc/security/cacerts
00673b5b.0
03e16f6c.0
08aef7bb.0
...

02-15 13:31:54.437: E/AndroidRuntime(824): java.lang.AssertionError: java.io.FileNotFoundException: /system/etc/security/cacerts.bks: open failed: ENOENT (No such file or directory)
02-15 13:31:54.437: E/AndroidRuntime(824):  at org.thoughtcrime.ssl.pinning.PinningTrustManager$SystemKeyStore.getTrustStore(PinningTrustManager.java:246)
02-15 13:31:54.437: E/AndroidRuntime(824):  at org.thoughtcrime.ssl.pinning.PinningTrustManager$SystemKeyStore.getPkixParameters(PinningTrustManager.java:209)
02-15 13:31:54.437: E/AndroidRuntime(824):  at org.thoughtcrime.ssl.pinning.PinningTrustManager$SystemKeyStore.<init>(PinningTrustManager.java:185)
02-15 13:31:54.437: E/AndroidRuntime(824):  at org.thoughtcrime.ssl.pinning.PinningTrustManager.<init>(PinningTrustManager.java:102)
...

**Comment by tomwhipple** [comment]
See pull request #2 for solution.
